In [1]:
import pandas as pd
import numpy as np

# 1.Getting Data Ready

In [105]:
# Read Data
heart_disease = pd.read_csv("heart-disease.csv")
heart_disease

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2       1  
2        2   0     2       1  
3        2   0     2       1  
4        2   0     2       1  
..     ...  ..   ...     ...  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0  

[303 rows x 14 columns]

In [106]:
# Check For Data Types
heart_disease.dtypes

age           int64
sex           int64
cp            int64
trestbps      int64
chol          int64
fbs           int64
restecg       int64
thalach       int64
exang         int64
oldpeak     float64
slope         int64
ca            int64
thal          int64
target        int64
dtype: object

In [107]:
# check for Null Values
heart_disease.isna().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [108]:
# Split Data
X = heart_disease.drop("target",axis=1)
y = heart_disease["target"]

In [109]:
# train, test split (100% -> 80% training data, 20% test data)
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)

# 2. Choose right estimator/alogrithm

In [110]:
# Use Random Forest Classifier
from sklearn.ensemble import RandomForestClassifier

# Create Random forest classifier
clf = RandomForestClassifier(n_estimators=200)
clf.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'auto',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_impurity_split': None,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 200,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

# 3. Fit the model/algorithm use it to make predictions on our data

In [111]:
# Fit/or Train the classifier
clf.fit(X_train,y_train)

RandomForestClassifier(n_estimators=200)

In [10]:
# score 100% for training data
clf.score(X_train,y_train)

1.0

# 4. Evaluating a model

In [112]:
# score for test data # 83%
clf.score(X_test,y_test)

0.7377049180327869

# 5. Improve a model

In [11]:
for i in range(10,301,10):
    clf = RandomForestClassifier(n_estimators=i);
    clf.fit(X_train,y_train);
    print("Score for estimator ",i," is ", clf.score(X_test,y_test));

Score for estimator  10  is  0.7868852459016393
Score for estimator  20  is  0.7868852459016393
Score for estimator  30  is  0.819672131147541
Score for estimator  40  is  0.8360655737704918
Score for estimator  50  is  0.8360655737704918
Score for estimator  60  is  0.819672131147541
Score for estimator  70  is  0.8524590163934426
Score for estimator  80  is  0.8032786885245902
Score for estimator  90  is  0.7868852459016393
Score for estimator  100  is  0.8360655737704918
Score for estimator  110  is  0.8524590163934426
Score for estimator  120  is  0.8032786885245902
Score for estimator  130  is  0.819672131147541
Score for estimator  140  is  0.819672131147541
Score for estimator  150  is  0.8524590163934426
Score for estimator  160  is  0.8688524590163934
Score for estimator  170  is  0.8360655737704918
Score for estimator  180  is  0.8524590163934426
Score for estimator  190  is  0.819672131147541
Score for estimator  200  is  0.8360655737704918
Score for estimator  210  is  0.85

# 6. Save

In [113]:
import pickle
pickle.dump(clf,open("Hear_disease_classifier_RF.pkl","wb"));

In [114]:
# loading
clfi = pickle.load(open("Hear_disease_classifier_RF.pkl","rb"));
clfi.score(X_test,y_test)

0.7377049180327869

In [97]:
#x1 = np.array([73,1,2,135,300,0,1,104,0,2.5,1,1,4])
#x1.reshape(1,13)
x1 = X_test.iloc[20]
type(x1)
x1 = x1.to_numpy ()
x1 = x1.reshape(1,-1)
x1

array([[1.2269e-01, 0.0000e+00, 6.9100e+00, 0.0000e+00, 4.4800e-01,
        6.0690e+00, 4.0000e+01, 5.7209e+00, 3.0000e+00, 2.3300e+02,
        1.7900e+01, 3.8939e+02, 9.5500e+00]])

In [115]:
clf.score(X_test,y_test)

0.7377049180327869

In [116]:
clf.predict(x1)

array([0], dtype=int64)

In [133]:
y_true = clf.predict(X_test)
confusion_matrix(y_true,y_test)

# Model Predict Vs   True Value
# Model predict correctly 16 positive that actual positive
# Model predict un-correctly 1 positive that actual negative
# Model predict un-correctly  15 positive that actual positive
# Model predict correctly 29 that actual negative


array([[16,  1],
       [15, 29]], dtype=int64)

In [135]:
y_true.shape

(61,)

# PART -2

In [11]:
## 0. Import 
import numpy as np
import pandas as pd

In [13]:
## 1. Get Data Ready
car_sales = pd.read_csv('car-sales-extended-missing-data.csv.csv')
car_sales.head()

Make Colour  Odometer (KM)  Doors    Price
0   Honda  White        35431.0    4.0  15323.0
1     BMW   Blue       192714.0    5.0  19943.0
2   Honda  White        84714.0    4.0  28343.0
3  Toyota  White       154365.0    4.0  13434.0
4  Nissan   Blue       181577.0    3.0  14043.0

In [14]:
## Check for Nan
car_sales.isna().sum()

Make             49
Colour           50
Odometer (KM)    50
Doors            50
Price            50
dtype: int64

In [15]:
## Option 1 (panda library functions)
## 1.1. Fill Missing DATA
## MAKE = 'Other','missing value'
car_sales["Make"].fillna("Other",inplace=True)
## Color = 'Other',
car_sales["Colour"].fillna("Other",inplace=True)
## Odometer (KM) = 'remove','average','median'
car_sales["Odometer (KM)"].fillna(car_sales["Odometer (KM)"].mean(),inplace=True)
## Doors = 4
car_sales["Doors"].fillna(5,inplace=True)
## Price = 'Avg, Remove'
car_sales["Price"].fillna(car_sales["Price"].mean(),inplace=True)


In [17]:
car_sales.isna().sum()

Make             0
Colour           0
Odometer (KM)    0
Doors            0
Price            0
dtype: int64

In [16]:
## Option2 with Sci-kit learn libray
car_sales_2 = pd.read_csv("car-sales-extended-missing-data.csv.csv")

In [17]:
## import 
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer

In [18]:
## Define Imputer (How to impute)
imp1 = SimpleImputer(strategy="constant",fill_value="Other")
imp2 = SimpleImputer(strategy="mean")
imp3 = SimpleImputer(strategy="constant",fill_value=5)

In [19]:
## How to Transform (column transform)
col1 = ["Make","Colour"]
col2 = ["Odometer (KM)"]
col3 = ["Doors"]

imputer = ColumnTransformer([ # list of tuple (Name,how,where)
    ("imp1",imp1,col1),
    ("imp2",imp2,col2),
    ("imp3",imp3,col3),
], # transformer 
    remainder="passthrough"
)

In [20]:
## Transfor
car_sales_2_filled = imputer.fit_transform(car_sales_2)
car_sales_2_filled

array([['Honda', 'White', 35431.0, 4.0, 15323.0],
       ['BMW', 'Blue', 192714.0, 5.0, 19943.0],
       ['Honda', 'White', 84714.0, 4.0, 28343.0],
       ...,
       ['Nissan', 'Blue', 66604.0, 4.0, 31570.0],
       ['Honda', 'White', 215883.0, 4.0, 4001.0],
       ['Toyota', 'Blue', 248360.0, 4.0, 12732.0]], dtype=object)

In [21]:
# Recreate
car_sales_2_filled = pd.DataFrame(car_sales_2_filled,columns=["Make","Colour","Odometer (KM)","Doors","Price"])
car_sales_2_filled.head()

Make Colour Odometer (KM) Doors    Price
0   Honda  White       35431.0   4.0  15323.0
1     BMW   Blue      192714.0   5.0  19943.0
2   Honda  White       84714.0   4.0  28343.0
3  Toyota  White      154365.0   4.0  13434.0
4  Nissan   Blue      181577.0   3.0  14043.0

In [22]:
car_sales_2_filled.dropna(inplace=True)

In [23]:
# check
car_sales_2_filled.isna().sum()

Make             0
Colour           0
Odometer (KM)    0
Doors            0
Price            0
dtype: int64

In [24]:
car_sales_2_filled

Make Colour Odometer (KM) Doors    Price
0     Honda  White       35431.0   4.0  15323.0
1       BMW   Blue      192714.0   5.0  19943.0
2     Honda  White       84714.0   4.0  28343.0
3    Toyota  White      154365.0   4.0  13434.0
4    Nissan   Blue      181577.0   3.0  14043.0
..      ...    ...           ...   ...      ...
995  Toyota  Black       35820.0   4.0  32042.0
996   Other  White      155144.0   3.0   5716.0
997  Nissan   Blue       66604.0   4.0  31570.0
998   Honda  White      215883.0   4.0   4001.0
999  Toyota   Blue      248360.0   4.0  12732.0

[950 rows x 5 columns]

In [25]:
## 1.2 Feature Encoding 
## Import
from sklearn.preprocessing import OneHotEncoder

In [26]:
## Create Encoder
onehot = OneHotEncoder()

In [27]:
## choose feature
cat_feature = ["Make","Colour","Doors"]

## Create Transformer

encoder = ColumnTransformer([
    ("encode",onehot,cat_feature)],
    remainder='passthrough'
)

In [28]:
## Transform
encoded = encoder.fit_transform(car_sales)
encoded

# Before encode => 1000,5
# After encoded => 1000,16, => 16-5 = 11
encoded

array([[0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        3.54310e+04, 1.53230e+04],
       [1.00000e+00, 0.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        1.92714e+05, 1.99430e+04],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        8.47140e+04, 2.83430e+04],
       ...,
       [0.00000e+00, 0.00000e+00, 1.00000e+00, ..., 0.00000e+00,
        6.66040e+04, 3.15700e+04],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        2.15883e+05, 4.00100e+03],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        2.48360e+05, 1.27320e+04]])

In [29]:
car_sales_encoded = pd.DataFrame(encoded)
car_sales_encoded.head()

0    1    2    3    4    5    6    7    8    9    10   11   12   13  \
0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   
1  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0   
2  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   
3  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   
4  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0   

         14       15  
0   35431.0  15323.0  
1  192714.0  19943.0  
2   84714.0  28343.0  
3  154365.0  13434.0  
4  181577.0  14043.0

In [30]:
## 1.3 Split Data
X = car_sales_encoded.drop(15,axis=1)
y = car_sales_encoded[15]

In [31]:
## Train test split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(800, 15)
(200, 15)
(800,)
(200,)


In [32]:
# 2. Choose the right estimator
# Regression
# RandomForestRegressor
from sklearn.ensemble import RandomForestRegressor
np.random.seed(555)
clf = RandomForestRegressor()
clf.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'criterion': 'mse',
 'max_depth': None,
 'max_features': 'auto',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_impurity_split': None,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [33]:
# 3. Fit Estimator
clf.fit(X_train,y_train)
clf.score(X_test,y_test)

0.19484579494971255

In [34]:
# 4. Evaluation

for i in range(10,300,10):
    clf = RandomForestRegressor(n_estimators=i)
    clf.fit(X_train,y_train)
    print(f'Accuracy{clf.score(X_test,y_test)} for {i} estimator')

Accuracy0.16902989411336067 for 10 estimator
Accuracy0.21706246146166486 for 20 estimator
Accuracy0.17121530601104828 for 30 estimator
Accuracy0.18846866317629052 for 40 estimator
Accuracy0.1741783601146044 for 50 estimator
Accuracy0.1751293000693679 for 60 estimator
Accuracy0.1853134267664276 for 70 estimator
Accuracy0.17530493322504004 for 80 estimator
Accuracy0.20754330618295191 for 90 estimator
Accuracy0.19495449192955128 for 100 estimator
Accuracy0.18731799014226913 for 110 estimator
Accuracy0.19635207780399178 for 120 estimator
Accuracy0.19466619764276405 for 130 estimator
Accuracy0.1908257890626427 for 140 estimator
Accuracy0.19921414919799418 for 150 estimator
Accuracy0.1851959101427183 for 160 estimator
Accuracy0.1953976107659423 for 170 estimator
Accuracy0.21247312605308855 for 180 estimator
Accuracy0.19459408012554757 for 190 estimator
Accuracy0.19752992727448848 for 200 estimator
Accuracy0.20757848139477353 for 210 estimator
Accuracy0.1990229338655578 for 220 estimator
Accu

In [45]:
from sklearn.linear_model import SGDRegressor
np.random.seed(4444)
clf = SGDRegressor(loss='epsilon_insensitive')
clf.get_params()

{'alpha': 0.0001,
 'average': False,
 'early_stopping': False,
 'epsilon': 0.1,
 'eta0': 0.01,
 'fit_intercept': True,
 'l1_ratio': 0.15,
 'learning_rate': 'invscaling',
 'loss': 'epsilon_insensitive',
 'max_iter': 1000,
 'n_iter_no_change': 5,
 'penalty': 'l2',
 'power_t': 0.25,
 'random_state': None,
 'shuffle': True,
 'tol': 0.001,
 'validation_fraction': 0.1,
 'verbose': 0,
 'warm_start': False}

In [46]:
clf.fit(X_train,y_train) # 950 // 15 // linear // bug >> rating 

SGDRegressor(loss='epsilon_insensitive')

In [47]:
clf.score(X_test,y_test)

-22718.348139790407

In [48]:
## End..................

In [57]:
## Problems 
from sklearn.datasets import load_boston
house = load_boston()
house_data = house['data']

house_target = house['target']
house.DESCR

".. _boston_dataset:\n\nBoston house prices dataset\n---------------------------\n\n**Data Set Characteristics:**  \n\n    :Number of Instances: 506 \n\n    :Number of Attributes: 13 numeric/categorical predictive. Median Value (attribute 14) is usually the target.\n\n    :Attribute Information (in order):\n        - CRIM     per capita crime rate by town\n        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.\n        - INDUS    proportion of non-retail business acres per town\n        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)\n        - NOX      nitric oxides concentration (parts per 10 million)\n        - RM       average number of rooms per dwelling\n        - AGE      proportion of owner-occupied units built prior to 1940\n        - DIS      weighted distances to five Boston employment centres\n        - RAD      index of accessibility to radial highways\n        - TAX      full-value property-tax rate per $10,000

In [58]:
housing = pd.DataFrame(house_data)
housing[13] = pd.Series(house_target)
housing

0     1      2    3      4      5     6       7    8      9     10  \
0    0.00632  18.0   2.31  0.0  0.538  6.575  65.2  4.0900  1.0  296.0  15.3   
1    0.02731   0.0   7.07  0.0  0.469  6.421  78.9  4.9671  2.0  242.0  17.8   
2    0.02729   0.0   7.07  0.0  0.469  7.185  61.1  4.9671  2.0  242.0  17.8   
3    0.03237   0.0   2.18  0.0  0.458  6.998  45.8  6.0622  3.0  222.0  18.7   
4    0.06905   0.0   2.18  0.0  0.458  7.147  54.2  6.0622  3.0  222.0  18.7   
..       ...   ...    ...  ...    ...    ...   ...     ...  ...    ...   ...   
501  0.06263   0.0  11.93  0.0  0.573  6.593  69.1  2.4786  1.0  273.0  21.0   
502  0.04527   0.0  11.93  0.0  0.573  6.120  76.7  2.2875  1.0  273.0  21.0   
503  0.06076   0.0  11.93  0.0  0.573  6.976  91.0  2.1675  1.0  273.0  21.0   
504  0.10959   0.0  11.93  0.0  0.573  6.794  89.3  2.3889  1.0  273.0  21.0   
505  0.04741   0.0  11.93  0.0  0.573  6.030  80.8  2.5050  1.0  273.0  21.0   

         11    12    13  
0    396.90  4.98  24.0  
1    396.90  9.14  21.6  
2    392.83  4.03  34.7  
3    394.63  2.94  33.4  
4    396.90  5.33  36.2  
..      ...   ...   ...  
501  391.99  9.67  22.4  
502  396.90  9.08  20.6  
503  396.90  5.64  23.9  
504  393.45  6.48  22.0  
505  396.90  7.88  11.9  

[506 rows x 14 columns]

In [59]:
# check
housing.isna().sum()

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
dtype: int64

In [61]:
## Split
X = housing.drop(13,axis=1)
y = housing[13]

In [65]:
## train test
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)

In [74]:
### Test with SGDRegressor
from sklearn.linear_model import SGDRegressor
sgd_clf = SGDRegressor()
sgd_clf.fit(X_train,y_train)
sgd_clf.score(X_test,y_test)
print(f'score with SGD Regression{sgd_clf.score(X_test,y_test)}')

score with SGD Regression-1.2559583291202632e+26


In [77]:
### Test with Ridge Regressing
from sklearn.linear_model import Ridge
r_clf = Ridge()
r_clf.fit(X_train,y_train)
r_clf.score(X_test,y_test)
print(f'score with Rige Regression {r_clf.score(X_test,y_test)}')

score with Rige Regression 0.6898616464690168


In [80]:
### Test with Random Forest Regressor
from sklearn.ensemble import RandomForestRegressor
rf_clf =RandomForestRegressor()
rf_clf.fit(X_train,y_train)
rf_clf.score(X_test,y_test)
print(f'score with Random Forest Regression {rf_clf.score(X_test,y_test)}')

score with Random Forest Regression 0.8349946109590524


In [82]:
### Test with SVM
from sklearn import svm
svm_clf = svm.SVR()
p = svm_clf.get_params()
svm_clf.fit(X_train,y_train)
svm_clf.score(X_test,y_test)
print(f'score with SVM {rf_clf.score(X_test,y_test)}')

score with SVM 0.8349946109590524


In [121]:
## Predict Future with our model
x= X_test.iloc[4]
x= x.to_numpy()
## Reshape
x = x.reshape(1,-1)

In [122]:
svm_clf.predict(x)

array([20.5325064])

In [131]:
svm_clf.predict(X_test)
y_true = svm_clf.predict(X_test)
y_test

141    1
236    0
260    0
142    1
248    0
      ..
31     1
28     1
119    1
249    0
230    0
Name: target, Length: 61, dtype: int64

In [136]:
from sklearn.metrics import confusion_matrix
#confusion_matrix(y_true,y_test)